version: 2
updates:
- package-ecosystem: cargo
  directory: "/consumer"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: lapin
    versions:
    - 1.6.6
    - 1.6.7
    - 1.6.8
    - 1.6.9
  - dependency-name: postgres
    versions:
    - 0.19.0
  - dependency-name: thiserror
    versions:
    - 1.0.23
- package-ecosystem: gomod
  directory: "/dispatcher"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: gomod
  directory: "/sensor"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: "/util"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/graphql"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: apollo-server
    versions:
    - 2.19.2
    - 2.20.0
    - 2.21.0
    - 2.21.1
    - 2.21.2
    - 2.22.1
    - 2.22.2
  - dependency-name: datasource-sql
    versions:
    - 1.4.0
- package-ecosystem: npm
  directory: "/web"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: npm
    versions:
    - 6.14.11
    - 7.10.0
    - 7.11.0
    - 7.5.2
    - 7.5.3
    - 7.5.4
    - 7.5.6
    - 7.6.0
    - 7.6.1
    - 7.6.2
    - 7.6.3
    - 7.7.0
    - 7.7.4
    - 7.7.5
    - 7.7.6
    - 7.8.0
    - 7.9.0
  - dependency-name: "@apollo/client"
    versions:
    - 3.3.10
    - 3.3.11
    - 3.3.12
    - 3.3.13
    - 3.3.14
    - 3.3.7
    - 3.3.8
    - 3.3.9
  - dependency-name: next
    versions:
    - 10.0.5
    - 10.0.6
    - 10.0.7
    - 10.0.8
    - 10.0.9
    - 10.1.1
    - 10.1.2
    - 10.1.3
  - dependency-name: styled-components
    versions:
    - 5.2.2
